volumes:
  db-init:
  db-data:

services:
  backend:
    build:
      context: ./
      dockerfile: ./docker_files/go/Dockerfile.local
    container_name: golang-sqlboiler
    volumes:
      - './src:/go/app'
    ports:
      - '8100:80'
    tty: true
    stdin_open: true
    env_file:
      - local.env
    depends_on:
      - rdb
  rdb:
    build:
      context: ./
      dockerfile: ./docker_files/mysql/Dockerfile.local
    container_name: golang-sqlboiler-rdb
    restart: on-failure:5
    ports:
      - '3666:3306'
    env_file:
      - local.env
    tty: true
    volumes:
      - db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake